### ISSUE TITLE
I'm playing as the piglin and the golden tools thing doesn't work, any help?

### ISSUE THREAD

**Issue by devteylow** [MoriyaShiine/extra-origins#102]
I've tried switching from and back to the piglin and it didn't work, and neither did leaving and rejoining. My game works perfectly otherwise.

**Comment by MoriyaShiine** [comment]
I have nothing to work with, I need more than just "it doesn't work"

**Comment by devteylow** [comment]
Alright, so originally it was working fine but after a bit of play time the durability started acting like vanilla durability. I don't know if that's intended or not, sorry. We're also running the TooManyOrigins mod, the Pehkui-2.0.0 mod, Origins-Classes, Origins, MobOrigins, Fabric-API 0.32.0, and extraorigins. Sorry for not giving enough info!

**Comment by MoriyaShiine** [comment]
Does this happen?
