### ISSUE TITLE
Piglin Nether Spawn Not Working

### ISSUE THREAD

**Issue by kirkusmaximus** [MoriyaShiine/extra-origins#11]
[latest.log](https://github.com/MoriyaShiine/extra-origins/files/5331168/latest.log)

Seem to have an issue with Spawning in the Nether as a Piglin. I spawn in the overworld and the logs show an error. If I die I seem to get the same error when I hit the respawn button.

I disabled everything but the origin mods to isolate the issue.

**Comment by MoriyaShiine** [comment]
This isn't on my end, I use the vanilla Origins ability. Report it on their github please.
