### ISSUE TITLE
Crashing/Failing to launch

### ISSUE THREAD

**Issue by YurieTheAkward** [MoriyaShiine/extra-origins#110]
I can't figure out how to get the extra origins to stop giving me this error message.
My fabric is up to date and I have Pehkui installed.
Thank you in advance.
![origins](https://user-images.githubusercontent.com/83554435/116825380-b491f900-ab54-11eb-9f6c-486889a33d5e.jpg)

**Comment by MoriyaShiine** [comment]
You need fabric api, the name is misleading
