### ISSUE TITLE
Second layer of head skin not showing with Inchling

### ISSUE THREAD

**Issue by missmaddles** [MoriyaShiine/extra-origins#111]
When I use the inchling origin, the second layer of my skin on my head won't show up. It doesn't fix itself even if I disable and re-enable the hat part of my skin, or if I disconnect and reconnect from the world. ((Its ok if there isn't a fix for it though haha)
![image](https://user-images.githubusercontent.com/64723558/116835889-46136200-ab79-11eb-8728-f444f34ef9df.png)

**Comment by MoriyaShiine** [comment]
The large head was removed a while ago (and with it the skin bug), you should update :p

**Comment by missmaddles** [comment]
Okay, thanks!
