### ISSUE TITLE
Inchling not an inch?

### ISSUE THREAD

**Issue by missmaddles** [MoriyaShiine/extra-origins#112]
Sorry to add another issue about the inchling-- I updated extra origins and for some reason i'm not tiny anymore? Even if I give myself an orb of origin and reset myself to inchling or use a command i'm still big. (I'm on the latest version of pehkui too now, that's what edits the player size iirc)

https://user-images.githubusercontent.com/64723558/116841251-77962880-ab8d-11eb-80d0-56dcbcf73dcb.mp4

https://user-images.githubusercontent.com/64723558/116841297-9ac0d800-ab8d-11eb-83f5-6326fb62575b.mp4

(videos were too big to upload in the same one, first is orb of origin, second is command)

**Comment by MoriyaShiine** [comment]
You need to use the scale command since updating from several versions ago breaks the player

**Comment by missmaddles** [comment]
Thank you!
