### ISSUE TITLE
Help! I'm Tiny[er]

### ISSUE THREAD

**Issue by niknaksnicsnac** [MoriyaShiine/extra-origins#114]
IDK how this happened but when I logged in today I was barely 2 pixels tall. I'm playing an inchling, so i expected to be small but...not this small.

When I change my origin I go back to normal Inchling height but no taller.

![image](https://user-images.githubusercontent.com/83800004/117393415-43c35600-af33-11eb-9a57-ae32b66dcf4a.png)

**Comment by MoriyaShiine** [comment]
This happens when the server crashes because of how origins works, I can't do anything other than suggest you find what crashes the server and prevent it
