### ISSUE TITLE
Inchling shrinks with Requiem

### ISSUE THREAD

**Issue by FourInchKnife** [MoriyaShiine/extra-origins#116]
I'm using Origins, Requiem (with its Pandemonium expansion), Pehkui, and Extra Origins. I'm using the latest version of each.

If I drop into demon mode and then merge back into my body while using the inchling origin, I get smaller and smaller. There are also a few other things that made me shrink (I think dying might have been one? Not certain on that one though), and with that combined with the way Requiem works, I don't think it's that mod.

**Comment by MoriyaShiine** [comment]
Report this to origins or requiem, I use vanilla origins methods and I can't do anything about this
