### ISSUE TITLE
Gigantism Curse

### ISSUE THREAD

**Issue by Althana** [MoriyaShiine/extra-origins#119]
Tried playing on my server but this always pops up, never does in singleplayer and all the mods on the server are up to date and on the same versions:
Registry remapping failed: Recieved ID map for minecraft:enchantment contains IDs unknown to reciever! - magna:gigantism_curse
 
![Capture2](https://user-images.githubusercontent.com/85924429/122006136-b960e400-cd73-11eb-8b16-6f63b585f669.JPG)

**Comment by MoriyaShiine** [comment]
I don't add any enchantments
