### ISSUE TITLE
Is Piglin compatible with weapon modules?

### ISSUE THREAD

**Issue by Petslime** [MoriyaShiine/extra-origins#124]
Hope you can add enhancements to the golden equipment in the medieval weapon module
https://github.com/Globox1997/MedievalWeapons

**Comment by MoriyaShiine** [comment]
You can add them yourself via a datapack using the extraorigins:golden_armor and extraorigins:golden_tools tags, but I'll make a PR too if you can wait for if/when they accept it

**Comment by MoriyaShiine** [comment]
Pull Request was made, you can check progress on it here https://github.com/Globox1997/MedievalWeapons/pull/26
