### ISSUE TITLE
Size is reset upon Inchling death

### ISSUE THREAD

**Issue by listerla** [MoriyaShiine/extra-origins#13]
After dying on a multiplayer server, I found myself two blocks tall once more but with the rest of the stats the same.

**Comment by kabadesu** [comment]
I came to report the same bug. This just happened to us with `extraorigins-16.jar` on 1.16.2. I'm using the mod with All of Fabric 3 2.1.3.

**Comment by MoriyaShiine** [comment]
I'm unable to replicate this on 1.16.3, and 1.16.2 is unsupported. Try to see if the modpack author can update the pack to 1.16.3.

**Comment by listerla** [comment]
I am using it on 1.16.3. Same bug, when I die I see myself as regular sized but with the same stats whilst others view me as small.

**Comment by MoriyaShiine** [comment]
Still can't replicate it, I always see myself as small. Does this happen with just Extra Origins and its dependencies?

**Comment by OasisAkari** [comment]
It always happens when another player in the near spawn point.
