### ISSUE TITLE
Invalid PowerTypeReference: no power type exists with id "extraorigins:all_that_glitters" and Ambiguity between arguments [scale, get, scale_type] and [scale, get, entity] with inputs: [base]

### ISSUE THREAD

**Issue by RimuruT3mpest** [MoriyaShiine/extra-origins#136]
Can someone please explain how to solve this issue?

_09:15:58.677
io.github.apace100.apoli.Apoli
Render thread
Invalid PowerTypeReference: no power type exists with id "extraorigins:all_that_glitters"
09:15:58.681
io.github.apace100.apoli.Apoli
Render thread
Invalid PowerTypeReference: no power type exists with id "extraorigins:all_that_glitters"
09:15:58.685
io.github.apace100.apoli.Apoli
Render thread
Invalid PowerTypeReference: no power type exists with id "extraorigins:all_that_glitters"
09:15:58.688
io.github.apace100.apoli.Apoli
Render thread
Invalid PowerTypeReference: no power type exists with id "extraorigins:all_that_glitters"
09:15:58.690
io.github.apace100.apoli.Apoli
Render thread
Invalid PowerTypeReference: no power type exists with id "extraorigins:all_that_glitters"
09:15:58.692
io.github.apace100.apoli.Apoli
Render thread
Invalid PowerTypeReference: no power type exists with id "extraorigins:all_that_glitters"
09:15:58.694
io.github.apace100.apoli.Apoli
Render thread
Invalid PowerTypeReference: no power type exists with id "extraorigins:all_that_glitters"
09:16:12.083
net.minecraft.class_2170
Render thread
Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
09:16:12.084
net.minecraft.class_2170
Render thread
Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
09:16:12.086
net.minecraft.class_2170
Render thread
Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
09:16:12.087
net.minecraft.class_2170
Render thread
Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
09:16:12.088
net.minecraft.class_2170
Render thread
Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
09:16:12.090
net.minecraft.class_2170
Render thread
Ambiguity between arguments [scale, get, scale_type] and [scale, get, entity] with inputs: [base]
09:16:12.091
net.minecraft.class_2170
Render thread
Ambiguity between arguments [scale, get, scale_type, entity] and [scale, get, scale_type, scalingFactor] with inputs: [0123]
09:16:12.092
net.minecraft.class_2170
Render thread
Ambiguity between arguments [scale, get, scale_type, scalingFactor] and [scale, get, scale_type, entity] with inputs: [0, -1, -.5, 1.2, .5, -1234.56]
09:16:12.093
net.minecraft.class_2170
Render thread
Ambiguity between arguments [scale, get, scalingFactor] and [scale, get, entity] with inputs: [0, -1, -.5, 1.2, .5, -1234.56]
09:16:12.094
net.minecraft.class_2170
Render thread
Ambiguity between arguments [scale, get, entity] and [scale, get, scalingFactor] with inputs: [0123]
09:16:12.095
net.minecraft.class_2170
Render thread
Ambiguity between arguments [scale, compute, scale_type, entity] and [scale, compute, scale_type, scalingFactor] with inputs: [0123]
09:16:12.096
net.minecraft.class_2170
Render thread
Ambiguity between arguments [scale, compute, scale_type, scalingFactor] and [scale, compute, scale_type, entity] with inputs: [0, -1, -.5, 1.2, .5, -1234.56]
09:16:12.097
net.minecraft.class_2170
Render thread
Ambiguity between arguments [scale, reset, scale_type] and [scale, reset, targets] with inputs: [base]
09:16:12.098
net.minecraft.class_2170
Render thread
Ambiguity between arguments [scale, delay, get, scale_type] and [scale, delay, get, entity] with inputs: [base]
09:16:12.099
net.minecraft.class_2170
Render thread
Ambiguity between arguments [scale, persist, reset, scale_type] and [scale, persist, reset, targets] with inputs: [base]
09:16:47.127
net.adriantodt.fallflyinglib.impl.FallFlyingAbilityTracker
Server thread
Player class_3222['Madelein3'/197, l='ServerLevel[EEEE]', x=-91.50, y=86.00, z=196.50] could not be synced because server networking isn't set up yet._

**Comment by MoriyaShiine** [comment]
I'm not really sure what's happening here, can you test with just Extra Origins? Also make sure all of your mods are up to date.

**Comment by RimuruT3mpest** [comment]
Extra origins alone?
