### ISSUE TITLE
Can't ride people as inchling

### ISSUE THREAD

**Issue by LittleThief78** [MoriyaShiine/extra-origins#140]
I'm using the 1.18 version and my friend just created a 1.18 Minecraft server. We have all the necessary dependency files but I can't ride anyone as the inchling. Everything else works but the riding mechanic.

**Comment by MoriyaShiine** [comment]
Seems to work fine for me. Are you sure you set the keybind?

**Comment by MoriyaShiine** [comment]
Any update?

**Comment by LittleThief78** [comment]
> Any update?

Sorry for the late response! I didn't get a notif for the other reply. Just checked and I did not in fact set a keybind. I thought that everything automatically had set buttons. Thank you for the help!
