### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by Bibels** [MoriyaShiine/extra-origins#141]
When I try to load the game with the mod it wont work. I think it might be because of this mod maybe? https://www.curseforge.com/minecraft/mc-mods/lato-origins

**Comment by Bibels** [comment]
Also it doesnt work in my friends minecraft server with tha same mod

**Comment by MoriyaShiine** [comment]
Lato Origins is known to steal my code, and for mixin reasons my code is incompatible with copies of itself. I can't do anything about this unfortunately
