### ISSUE TITLE
Minecraft crashes when i try to start it on 1.16.5

### ISSUE THREAD

**Issue by KaydenTrax** [MoriyaShiine/extra-origins#142]
so when i try to Launch Minecraft on 1.16.5 with the extra Origins mod and other mods it crashes and it says The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'extraorigins'!
Exit-Code: -1
 i have pehkui and Fabric API installed

**Comment by MoriyaShiine** [comment]
1.16.5 is no longer supported and you gave no crash log. I can only assume you have Pehkui 3.0.0 installed; 1.16 needs Pehkui 2.6.0
