### ISSUE TITLE
XRAY with Inchling

### ISSUE THREAD

**Issue by itsdinkd** [MoriyaShiine/extra-origins#144]
![image](https://user-images.githubusercontent.com/35115304/146079408-88cd592f-a4f7-4ac0-a3fa-4cbaa5558b8c.png)

Apparently, if you add the mods Better Third Person View for 1.18 and choose a inchling, you can x-ray. 

I also have Nimble added into my modpack, so it might be a mixture of both perspective mods.

**Comment by MoriyaShiine** [comment]
Inchling's size change relies on [Pehkui](https://github.com/Virtuoel/Pehkui), I suggest reporting it there instead; I can't do much without invading on base Pehkui stuff

**Comment by Virtuoel** [comment]
Appears to be fixed in the latest version of Nimble.
