### ISSUE TITLE
I cant eat suger with the inchling 1.18.1

### ISSUE THREAD

**Issue by Turtlegame8** [MoriyaShiine/extra-origins#145]
Please read before making your issue:

The issue tracker is not the place for suggestions, please join the discord for that.

If your issue fits any of the following criteria, it will be closed without a comment:
-You do not provide a crash report or log if the game crashed.
-Your issue has to do with using the wrong version of or not having a dependency. The fabric loader tells you exactly what you need to do.
-You are using an outdated version of the mod, do not provide the version of the mod you are using, or are using "latest." "Latest" doesn't mean anything to developers, so please avoid using the term and state the specific version, even if it does happen to be the latest release at the time.

You may delete this text when creating your issue.

**Comment by Turtlegame8** [comment]
i cant eat suger with the inchling

**Comment by MoriyaShiine** [comment]
You never were able to, that is a data pack made by someone else. I don't know where it is or if it exists but I'd check the origins discord
