### ISSUE TITLE
Reports on Inchling being very vulnerable 

### ISSUE THREAD

**Issue by itsdinkd** [MoriyaShiine/extra-origins#148]
Fabric 0.12.12
1.18.1
Latest Extra Origins

--

I am getting reports that players who use Inchling are getting one shot very easily while being equipped with armor that outputs over 40 and 15 toughness. whereas if they wear the same armor as human they are not getting one shot. A zombie with a diamond sword for example is one shotting them, or so the report says. 

Is this a bug in my modpack, or is this to be expected? They said it wasn't doing this before

**Comment by MoriyaShiine** [comment]
I'm not sure, but armor caps at 30; anything over that doesn't do anything. Can you test how much health remains when a human is hit with a zombie holding diamond sword

**Comment by MoriyaShiine** [comment]
This is an oversight lol, apparently every origin takes extra damage; related to https://github.com/MoriyaShiine/extra-origins/issues/151

**Comment by itsdinkd** [comment]
Oh damn lmao that's not good, but great find. The initial problem was due
to Hardcore Revival. Sorry for not reporting back on the cause
