### ISSUE TITLE
Unsure how to use the riding power, 1.17 

### ISSUE THREAD

**Issue by utteralex** [MoriyaShiine/extra-origins#149]
Hello!

Sorry if I sound dumb, my friends and I made a server and our inchling is a bit difficult to navigate in terms of riding players. We can't figure out how exactly to do it, most of us are new ish to the game and tried looking at past issues and the wiki logs to figure it out but none of us can seem to make it work. I saw it should work in our version, since we are using the 1.17 and everything else seems to be working. We just need a little assistance on how to exactly activate the power. We know G activates the primary power just unsure how to activate the riding aspect. Hope to hear from you soon, and again sorry if its any trouble!

**Comment by MoriyaShiine** [comment]
Secondary key, it's unbound by default
