### ISSUE TITLE
Elder Guardian mining fatigue effect not working 

### ISSUE THREAD

**Issue by visluu** [MoriyaShiine/extra-origins#150]
When I was experimenting with the new 1.18 extra origins specifically the Guardian origin, I noticed that the main ability of the Elder Guardian origin didn't work when I triggered the ability. It doesn't spawn an area of effect of mining fatigue but it still uses up the ability charge. This issue didn't  happen to me in the 1.17 version of extra origins and I don't know a fix for it.

**Comment by MoriyaShiine** [comment]
Extra Origins doesn't have an elder guardian

**Comment by visluu** [comment]
ah my bad, I sent it to the wrong issue board. My apologies!

**Comment by MoriyaShiine** [comment]
No worries lol
