### ISSUE TITLE
Taking increased damage from lava/fire without any powers

### ISSUE THREAD

**Issue by Maxmani** [MoriyaShiine/extra-origins#151]
For some reason, when the version 1.18-5 of Extra Origins is installed, even when using the default Human Origin, lava deals 2.5 hearts of damage instead of 2. Fire damage seems slightly increased too. Removing Extra Origins makes lava damage normal again.

I've tried removing every other mod but the dependencies, and I tried downgrading to 1.18-4 and 1.18-2, but it's also an issue in those versions. 1.18-1, however, works as intented. Most likely unrelated, but removing every Power and Origin from the jar file itself also resulted in no change in 1.18-5.

Fabric Loader version is 0.12.12 and dependencies are up-to-date.

[Mod list](https://gist.github.com/Maxmani/60388f0090837fd7b6dd535d374c5d84)

**Comment by MoriyaShiine** [comment]
This happens with all damage apparently, not just fire; fixed in 1.18-6
