### ISSUE TITLE
Crash on 1.16.5 (both server and client)

### ISSUE THREAD

**Issue by TR27XD** [MoriyaShiine/extra-origins#155]
I just got a crash on my server after uploading this mod. 
I'm using ''extraorigins-1.16.5-12.jar'' and ''Origins-1.16.5-0.7.3.jar''.
Crash log is attatched below.

[latest.log](https://github.com/MoriyaShiine/extra-origins/files/7900853/latest.log)

My client also crashed on load.

[crash-2022-01-19_21.56.54-client.txt](https://github.com/MoriyaShiine/extra-origins/files/7900884/crash-2022-01-19_21.56.54-client.txt)

I verified, the crash does not happen without extraorigins installed.

**Comment by MoriyaShiine** [comment]
Clone of #142
