### ISSUE TITLE
Can't get Truffle mycelium to work

### ISSUE THREAD

**Issue by zettania** [MoriyaShiine/extra-origins#158]
On a fully updated version of the mod, but can't get the Truffle function to work to make soil into mycelium. Can someone specify fully what needs to be done, or if it's just a glitch

**Comment by MoriyaShiine** [comment]
Sneak + use (defaults to shift + right click) on soil (dirt, grass, etc), as per the power's text

**Comment by Set2Minecraft** [comment]
I am having the same issue but in my case I see the mycelium but it just reverts to what it was before. Dont know why.
