### ISSUE TITLE
Truffle Mycelium Effects Don't Work

### ISSUE THREAD

**Issue by toErIpNid** [MoriyaShiine/extra-origins#160]
Tried testing the Truffle out in single player in preparation for the server, I noticed that only the movement speed cap actually did anything. Even when standing on Mycelium, most of the caps' powers don't seem to work. I don't get increased jump height, and my attack speed doesn't seem to go any faster when using the red cap. I've tried jumping over a fence when switching to the movement one while standing on mycelium and I couldn't hop it.

**Comment by MoriyaShiine** [comment]
Misunderstanding of what the powers do, clarified in discord dms
