### ISSUE TITLE
Truffle Mycelium doing weird stuff

### ISSUE THREAD

**Issue by Set2Minecraft** [MoriyaShiine/extra-origins#162]
Version 1.18-8

Issue: When sneaking + right clicking with empty hand on soil block, mycelium texture will appear for a second, then revert to the previous block, attempted on dirt, grass, and podzol. Also 0 hunger is used.

Mods:
(the indented are showing that the un-indented above is required for the mod too work, though I do not know what cross-mod issues this would have with this issue)

- Sodium
- lambdynamic lights
- Logical zoom
- Origins
       - Penkui
               - extra Origins
- malib
      - minihud
      - litematica
- shulkerbox tooltip
-  Mod menu
- Fabric Language Scala
       - Inventory HUD
-Bobby

**Comment by MoriyaShiine** [comment]
I suggest reporting to https://github.com/apace100/apoli/issues. I use exclusively vanilla origins stuff here, so I can't do anything about this unfortunately.
