### ISSUE TITLE
Extra Origins not letting me start up a server

### ISSUE THREAD

**Issue by Justindraak** [MoriyaShiine/extra-origins#163]
I'm trying to make a 1.16.5 Origin-centered server for me and my homies, but everytime i try to start up the server (using aternos) it says something like couldn't initiate entrypoint 'main' due to errors provided by  Extra Origins. this doesnt happen when i start up my minecraft client (no matter which version of the mod) and this also doesnt happen when i use extraorigins-1.16.5-1.jar or extraorigins-1.16.5-2.jar, but then when i choose inchling, the server crashes (crash log below).
(Main error is at the latest version for 1.16.5, extraorigins-1.16.5-12.jar, of which the crash log is: https://mclo.gs/vPeQG4v  , the inchling crash's log is the file attached)
[inchling crash.txt](https://github.com/MoriyaShiine/extra-origins/files/8049597/inchling.crash.txt)
.

**Comment by MoriyaShiine** [comment]
Clone of #142 

Using 1.17 or or 1.18 would fix it, as you have already figured out lol

**Comment by Justindraak** [comment]
> Hello. I had a same problem. You should try to use Pehkui 2.1.0. Works for me!

doesnt work for me :(
