### ISSUE TITLE
Mod Page Tagged Wrong

### ISSUE THREAD

**Issue by ashyashton** [MoriyaShiine/extra-origins#168]
When making a Forge profile in the CF app, the mod pops up despite being a Fabric-only mod, which isn't supposed to happen. You are totally valid for not wanting a Forge version of your mod to be made, but having it pop up on this list just clogs it up for people trying to find more origins for the Forge version of the Origins mod, so I would highly recommend getting that sorted.

**Comment by MoriyaShiine** [comment]
Curseforge removed the fabric category a while ago in favor of marking files per loader, and all of my files are marked as fabric. No idea why it would be showing up on forge searches, but I have no control over a curseforge bug unfortunately.
