### ISSUE TITLE
miss file  minecraft:extraorigins:spore 

### ISSUE THREAD

**Issue by ali7757** [MoriyaShiine/extra-origins#169]
i try to uninstalled and installed but nothing happen the Problem is still :CC 
![2](https://user-images.githubusercontent.com/54441077/154791935-8ee5a19e-1684-4e9c-950e-939a9a67a82d.png)

**Comment by MoriyaShiine** [comment]
Make sure the server and client have the same version of the mod

**Comment by ali7757** [comment]
the server have same version of mod
