### ISSUE TITLE
Piglin Origin Corrupts when transitioning from nether to overworld

### ISSUE THREAD

**Issue by Blanchdog** [MoriyaShiine/extra-origins#170]
Version: 1.17-8
[latest.log](https://github.com/MoriyaShiine/extra-origins/files/8144780/latest.log)

The Piglin origin has a bug that causes the player to lose connection to the server when attempting to exit the nether to the overworld. From then on, the player cannot log into the server; instead the game get's as far as "loading terrain" and then fails with "connection lost".

**Comment by MoriyaShiine** [comment]
I don't see anything that would indicate Extra Origins causes this. Does it happen on 1.18?

**Comment by MoriyaShiine** [comment]
Unable to reproduce
