### ISSUE TITLE
Lectern crash.

### ISSUE THREAD

**Issue by RageQuitAmy** [MoriyaShiine/extra-origins#174]
Issue:
You may delete this text when creating your issue.
Hi, so my friend made a pack which has this mod in it. 2 people have reported an issue where their game crashes when a lectern is placed. I couldn't get anything from the crash report. Also looked at the log and I couldn't understand it. So I removed the mods one by one until I found the problem. I removed the extra origins mod and everything worked okay. I also tested the Pehkui mod just in case it was that and that worked fine. 

Versions:
1.18.-3 which is used in the pack and 1.16.5-13 which someone used in their single player world. The pack is The Afterlife.

[message.txt](https://github.com/MoriyaShiine/extra-origins/files/8356537/message.txt)
[crash-2022-03-24_15.02.43-client.txt](https://github.com/MoriyaShiine/extra-origins/files/8356538/crash-2022-03-24_15.02.43-client.txt)
And here is a link that someone sent me that has their crash report. https://bytebin.lucko.me/s9F64s1wPy

**Comment by MoriyaShiine** [comment]
clone of #173
