### ISSUE TITLE
Jockey doesnt work on itchling on a server

### ISSUE THREAD

**Issue by MythicqI** [MoriyaShiine/extra-origins#176]
1.16.5,
![image](https://user-images.githubusercontent.com/103467720/162851482-932853ac-eff6-4a01-9339-d70633b438c9.png)

cannot use itchling ability. second ability key set to z and it doesnt work

**Comment by MoriyaShiine** [comment]
Clone of #131

**Comment by MythicqI** [comment]
> Clone of #131

i said the version tho, how do i fix it

**Comment by MoriyaShiine** [comment]
Read the issue, Jockey does not exist on 1.16
