### ISSUE TITLE
extraorigins:modify size problem

### ISSUE THREAD

**Issue by NachoIannizzotto** [MoriyaShiine/extra-origins#177]
I'm working on my own origin using the extra origins modify size power, in a toggle ability, somehow the modify size is not returning the correct scale. By default the origin is 0.5 size (working) but when toggled, the size changes to 1.0, instead of 2.0.

The code:

{
    "type": "origins:multiple",
    "invis": {
        "type": "origins:invisibility",
        "render_armor": false,
        "condition": {
            "type": "origins:power_active",
            "power": "*:sizetoggle",
            "inverted": true
        }
    },
    **"base_height": {
        "type": "extraorigins:modify_size",
        "scale": 0.5,
        "condition": {
            "type": "origins:power_active",
            "power": "*:sizetoggle",
            "inverted": true
        }
    },**
    "base_speed": {
        "type": "origins:conditioned_attribute",
        "modifier": {
            "attribute": "minecraft:generic.movement_speed",
            "operation": "addition",
            "value": 0.025,
            "name": "Increased sprinting speed"
        },
        "condition": {
            "type": "origins:power_active",
            "power": "*:sizetoggle",
            "inverted": true
        }
    },
    "base_health": {
        "type": "origins:conditioned_attribute",
        "modifier": {
            "attribute": "minecraft:generic.max_health",
            "operation": "addition",
            "value": -10.0,
            "name": "Increased sprinting speed"
        },
        "condition": {
            "type": "origins:power_active",
            "power": "*:sizetoggle",
            "inverted": true
        }
    },
    **"big_height": {
        "type": "extraorigins:modify_size",
        "scale": 2.0,
        "condition": {
            "type": "origins:power_active",
            "power": "*:sizetoggle"
        }
    },**
    "big_speed": {
        "type": "origins:conditioned_attribute",
        "modifier": {
            "attribute": "minecraft:generic.movement_speed",
            "operation": "addition",
            "value": -0.025,
            "name": "Increased sprinting speed"
        },
        "condition": {
            "type": "origins:power_active",
            "power": "*:sizetoggle"
        }
    },
    "big_health": {
        "type": "origins:conditioned_attribute",
        "modifier": {
            "attribute": "minecraft:generic.max_health",
            "operation": "addition",
            "value": 10.0,
            "name": "Increased sprinting speed"
        },
        "condition": {
            "type": "origins:power_active",
            "power": "*:sizetoggle"
        }
    },
    "big_transform": {
        "type": "origins:active_self",
        "entity_action": {
            "type": "origins:play_sound",
            "sound": "minecraft:entity.elder_guardian.curse",
            "volume": 1,
            "pitch": 0.4
        },
            "condition": {
                "type": "origins:power_active",
                "power": "*:sizetoggle"
        },
        "key": "key.origins.ternary_active"
    },
    "big_transform2": {
        "type": "origins:active_self",
        "entity_action": {
            "type": "origins:play_sound",
            "sound": "minecraft:entity.enderman.scream",
            "volume": 1,
            "pitch": 0.6
        },
            "condition": {
                "type": "origins:power_active",
                "power": "*:sizetoggle",
                "inverted": true
        },
        "key": "key.origins.ternary_active"
    }
}

**Comment by MoriyaShiine** [comment]
It looks like both are applying (0.5*2=1). Make sure to disable the base size

**Comment by NachoIannizzotto** [comment]
> Owner

If I have to disable it, how I set the "base size" to be half block?

**Comment by MoriyaShiine** [comment]
Disable it conditionally so when you have the 2x mode on, you don't have the 0.5x modifier; see the origins discord datapack help channels for support
