### ISSUE TITLE
trying to ride players/jockey breaks inchling climbing

### ISSUE THREAD

**Issue by taigasoda** [MoriyaShiine/extra-origins#180]
### Mod version

1.18.2

### A description of the issue

In 1.18.2 my friend cannot ride on my shoulder when he presses G and it completely breaks his ability to climb and jockey doesn't work anyway, he changed keybind to try it out but it still doesn't work

**Comment by MoriyaShiine** [comment]
G is not the keybind you use. Make sure to set your secondary key in controls
