### ISSUE TITLE
Inchling riding player bug

### ISSUE THREAD

**Issue by CSBoatman** [MoriyaShiine/extra-origins#184]
### Mod version

1.18-9

### A description of the issue

My server runs mc 1.18.1 and as an inchling when I ride on other players I show up on the other player inside their neck/head. As the inchling I can't see anything other than the other person's head and from the other person's perspective they say that my player model blocks their vision as well

![2022-06-07_12 33 52](https://user-images.githubusercontent.com/53665260/172957080-99e850e8-c122-4de2-96df-ca6c1d4cb7f4.png)
.

**Comment by MoriyaShiine** [comment]
Does this happen on 1.18.2?

**Comment by MoriyaShiine** [comment]
I have just updated to 1.19. Does it happen there? You do not need to check 1.18.2

**Comment by MoriyaShiine** [comment]
Unable to reproduce
