### ISSUE TITLE
1.19 issue with truffle powers being unknown to the receiver 

### ISSUE THREAD

**Issue by Echobine** [MoriyaShiine/extra-origins#187]
### Mod version

1.19

### A description of the issue

![IMG_1682](https://user-images.githubusercontent.com/97688391/176980460-d76f0ea6-9e16-4c73-9b1e-c9c36b80eafb.jpg)

Previously it had an issue with Pehkui and the receiver not recognizing scaling commands. It said nothing about having issues with Extra origins. I changed the version of Pehkui to [1.14.14 - 1.19] Pehkui 3.3.3 and now it's displaying the error above.  

I've had this issue on 1.18 as well and just had to use an older version.

**Comment by MoriyaShiine** [comment]
Can't reproduce. Make sure the server and all clients have the same version of all mods
