### ISSUE TITLE
Fabric server crashes (its aparently coming from the mod)

### ISSUE THREAD

**Issue by YuriGen2423** [MoriyaShiine/extra-origins#188]
### Mod version

extraorigins-1.19-1.jar

### A description of the issue

its apparently coming from the mod
I'm probably doing smth wrong bc it works fine on some hosts

### Log or crash report

https://gist.github.com/YuriGen2423/4bc70626ed55eb1a0ce69614f24908b5

**Comment by MoriyaShiine** [comment]
Clone of #185
