### ISSUE TITLE
inchling cant ride on other players at all.

### ISSUE THREAD

**Issue by SpaceReaper0** [MoriyaShiine/extra-origins#189]
### Mod version

1.18-12

### A description of the issue

when I right-click to ride on another player, nothing happens. mods on the server: https://drive.google.com/drive/folders/1Hwd0SHoleNKY95irtF5CfOKFiml8U3FK?usp=sharing

**Comment by MoriyaShiine** [comment]
It's not a right click function, you use the secondary key (as indicated next to the power name)
