### ISSUE TITLE
Allay Origin Lags the Server

### ISSUE THREAD

**Issue by itsactuallyezra** [MoriyaShiine/extra-origins#190]
### Mod version

1.19

### A description of the issue

Started up a modded server with my friends, and had your Extra Origins on. Worked great, right up until someone chose the Allay. The moment the Allay was in play, TPS dropped drastically, everything was teleporting. It's probably worth noting that I also had Witherborn Origins, and Elemental Origins on the server. When there were 2 players with the Allay, the game became unplayable (250~ ticks behind). And yes this was also re-created in Singleplayer. 

I'm hosting on Apex, and got the developers there to help me troubleshoot. After we finished, they recommended that I make a bug report, so here I am.

**Comment by MoriyaShiine** [comment]
Allay isn't part of Extra Origins
