### ISSUE TITLE
A Mild Floran Fallacy

### ISSUE THREAD

**Issue by Rosemary225** [MoriyaShiine/extra-origins#198]
### Mod version

All Versions

### A description of the issue

Florans are carnivores. I feel a more fitting challenge would be for them to be restricted to eating raw meats. That fits more in line with how Starbound describes them.

**Comment by MoriyaShiine** [comment]
Floran is inspired by Starbound, not directly copied from it

**Comment by Rosemary225** [comment]
You still could've made it make more sense.

**Comment by MoriyaShiine** [comment]
It's a plant person, plants utilize photosynthesis. I don't see the problem :p

The name is irrelevant, I could have picked anything plant related and it would still work with what it is now
