### ISSUE TITLE
game got homesick... couldn't handle it anymore... crashed

### ISSUE THREAD

**Issue by superon** [MoriyaShiine/extra-origins#20]
extraorigins-1.16.4-4
fabric-api-0.28.1+1.16
other mods in the log
https://pastebin.com/2sq9CNV2
was just standing there hanging out when this happened

**Comment by MoriyaShiine** [comment]
:how:

**Comment by superon** [comment]
skillz?

**Comment by MoriyaShiine** [comment]
fixed as of 1.16.4-5
