### ISSUE TITLE
Mounting Inchlings are "flying" other peoples head

### ISSUE THREAD

**Issue by Smuthytrinker** [MoriyaShiine/extra-origins#202]
### Mod version

1.19.2

### A description of the issue

Hey, firstly great work with the mod / extra origins, my friends and I are big fans of your work!

We are playing on a 1.19.2 Server and we noticed a little bug, inchlings are floating about a block too high over the other players head. I saw that you fixed it in the 1.19.3 version of the mod, but sadly we cant upgrade to 1.19.3 because of other mods in our modpack.
Would you maybe be so kind and make a 1.19.2 Version with the fix? (Only if it's not taking too much time from you.) We would really appreciate that!

Regardless if you do it or not, we wish you a wonderful day!

**Comment by MadBeeTV1** [comment]
This happens to me also, have you found a fix?

**Comment by MoriyaShiine** [comment]
Didn't realize this was open, clone of #197 / #199

**Comment by Kierecko** [comment]
> Didn't realize this was open, clone of #197 / #199

Friend of OP, the problem was that we can't update the mods so the fix from the other issues doesn't work for us. I guess your response means that there will never be a 1.19.2 fix for it though?
