### ISSUE TITLE
Server will not start when Extra Origins is installed on 1.19.4 fabric (with sodium, lithium, and phosphor)

### ISSUE THREAD

**Issue by CrashTestJava** [MoriyaShiine/extra-origins#206]
### Mod version

extraorigins-1.19-5.jar

### A description of the issue

I have a shockbyte server. When i take the mod out of the server mods folder it starts but when it is it does not start. The other mods I have in my server mods folder are as follows: phosphor-fabric-mc1.19.x-0.8.1.jar, Pehkui-3.7.2+1.14.4-1.19.4.jar, lithium-fabric-mc1.19.4-0.11.1.jar, sodium-fabric-mc1.19.4-0.4.10+build.24.jar, fabric-api-0.78.0+1.19.4.jar, and of course Origins-1.19.4-1.9.0.jar. Please fix this soon!!

**Comment by MoriyaShiine** [comment]
No log, closing. Feel free to reopen once log is attached
