### ISSUE TITLE
inchling hitbox is wider than it was in previous versions

### ISSUE THREAD

**Issue by shefithecat** [MoriyaShiine/extra-origins#212]
### Mod version

1.20-1

### A description of the issue

while playing with the inchling origin i noticed that i would not be able to fit into some crevices that i used to be able to in older versions of the mod a quick check at the hitbox made me realize that the hitbox is wider than it was (im not sure if this is related but when riding players i was stuck inside their head instead of being on it)

**Comment by MoriyaShiine** [comment]
This is intentional as an attempt to make then easier to hit

**Comment by shefithecat** [comment]
fair enough
