### ISSUE TITLE
 extraorigins$preventHittingPlayerMount

### ISSUE THREAD

**Issue by V-lpen** [MoriyaShiine/extra-origins#214]
### Mod version

1.20-2

### A description of the issue

Fix for #211  broke my datapack and several others involving picking players up. Specifically my "pick up players" datapack which I can provide privately for testing if you need

, but pretty much, I can no longer interact with a player I have picked up, therefore I cannot "use" the player on my head to force them to dismount anymore.  
This also will mess with other datapacks that allow players to grab a player for mechanics reasons like[ this](https://www.curseforge.com/minecraft/mc-addons/rain-world-origins)

Can some sort of check be done for this bug fix for only inchling / players that the inchling is riding?

**Comment by MoriyaShiine** [comment]
I wasn't expecting this to cause issues that fast haha, I'll fix it tomorrow

**Comment by V-lpen** [comment]
haha no worries! Thanks for being quick on fixing it! :D  I had made a custom pick up players for my server and noticed the issue almost immediately , took me awhile to find what caused it

**Comment by MoriyaShiine** [comment]
Oops sorry I forgot lol, fixed now
