### ISSUE TITLE
there isn't a 1.20.2 version. i cant use it on aternos

### ISSUE THREAD

**Issue by JizzyJack** [MoriyaShiine/extra-origins#217]
### Mod version

1.20.1

### A description of the issue

there isn't a 1.20.2 version. it says in tiny words 1.20.1 i cant use it on aternos

![Screenshot 2023-12-04 211952](https://github.com/MoriyaShiine/extra-origins/assets/152860111/8d2e148e-3981-405c-bb5e-39b22b1b5e9c)

**Comment by MoriyaShiine** [comment]
Not a bug, there is no 1.20.2 version at the moment

**Comment by JizzyJack** [comment]
> Not a bug, there is no 1.20.2 version at the moment

could you please make one?
