### ISSUE TITLE
Attack_Damage_Multiplier

### ISSUE THREAD

**Issue by TeyTey428** [MoriyaShiine/extra-origins#219]
### Mod version

extraorigins-1.18-12.jar

### A description of the issue

loading a world on a server would crash and give the error "Attack_Damage_Multiplier" which stopped after removing extra origins and the server booted up. I don't really have anything else to add since the crash report gave so little information. I wish you luck and a wonderful day

**Comment by MoriyaShiine** [comment]
I can't do anything without a crash report, and 1.18 is unsupported
