### ISSUE TITLE
Climbing stopped working

### ISSUE THREAD

**Issue by keep-land** [MoriyaShiine/extra-origins#220]
### Mod version

6.326

### Climbing has stopped working

I've been playing with multiple mods, and they've all been going pretty smooth, but recently the Inchling Climbing has stopped working. I went into the nether for the first time, it was working. I came out, started walking, then got glitched back to the opening of the portal (still on over world), and it stopped working. Can't climb walls, or blocks.

Im playing this mod through "dark RPG"

**Comment by MoriyaShiine** [comment]
6.326 isn't a version
Check if you toggled climb with the keybind, it's a vanilla Origins power. If climb has stopped working, report it to Origins

**Comment by keep-land** [comment]
i figured it out, i didnt know much about these mods so i was confused. thank you
