### ISSUE TITLE
Server crash with ExtraOrigins 1.20.1

### ISSUE THREAD

**Issue by ang3llx** [MoriyaShiine/extra-origins#221]
### Mod version

1.20.1

### A description of the issue

Hello! When starting up my server, using Aternos, fabric version 1.20.1 (0.15.2), it would crash. In the log, it says: 

**[main/ERROR]: Minecraft has crashed!
 net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: ATTACK_DAMAGE_MODIFIER**

I saw a post talking about this, saying it could be extraorigins, and it was :(
When I take it out of the mods folder, the server loads up perfectly fine but with extraorigins it crashes!

Please help me with this issue! 

### Log or crash report

https://mclo.gs/LnvVHxm

**Comment by MoriyaShiine** [comment]
Update Extra Origins, you're 3 versions behind (fixed in 1.20-4) :p
