### ISSUE TITLE
Aternos Crash Issue!

### ISSUE THREAD

**Issue by InvTem** [MoriyaShiine/extra-origins#222]
### Mod version

1.19.2

### A description of the issue

Hello! I have a server on Aternos that was working perfectly fine for a few days but is now crashing due to Extra Origins. I have no idea why it's suddenly crashing. I'm using Fabric Loader 0.15.2,  Aternos told me to come here for more extensive help. I've read a few of the issues for help on here as well and haven't run into anything that could help. Thanks for your time!

Here is the crash log just in case my log in gist is funky (For some reason my computer messes it up sometimes when pasting): [https://mclo.gs/9op2PRg](https://mclo.gs/9op2PRg)

### Log or crash report

https://gist.github.com/InvTem/20452e3d9501c894a498ad2777565757

**Comment by JamesDesrosiers** [comment]
I'm noticing the same issue on line 15, column 18. With "pack_format".

``` 
[13:40:23] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.15.5
[13:40:23] [ForkJoinPool-1-worker-7/WARN]: The mod "extra_classes_origins" contains invalid entries in its mod json:
- Unsupported root entry "pack_format" at line 15 column 18
[13:40:23] [ForkJoinPool-1-worker-7/WARN]: The mod "mermaid" contains invalid entries in its mod json:
- Unsupported root entry "pack_format" at line 15 column 18
```

If I have time, I'll try to find a fix.

**Comment by MoriyaShiine** [comment]
Completely forgot this was open, clone of #216 

Either update to 1.20 or use the fix mod pinned in the extra-origins channel on the discord

**Comment by Poopooracoocoo** [comment]
> Either update to 1.20 or use the fix mod pinned in the extra-origins channel on the discord

If a fix was already made for older versions, why not publish it on CF and MR?

**Comment by MoriyaShiine** [comment]
It's not an Extra Origins update, it's a separate mod that patches the original jar files
