### ISSUE TITLE
Can't change Magic Spore

### ISSUE THREAD

**Issue by ApoWillow** [MoriyaShiine/extra-origins#223]
### Mod version

Extra Origins 1.20-4

### A description of the issue

When changing Magic Spores in the Truffle origin, the gui (the white bar that goes up before changing to that magic spore) gets stuck and doesn't change the origin, this was on my modded multiplayer server and we don't know what is causing it. 
![2023-12-31_20 32 56](https://github.com/MoriyaShiine/extra-origins/assets/97743076/03188da2-73a6-4ca8-9246-96fab0470bc8)

**Comment by MoriyaShiine** [comment]
Is this still an issue? I've never been able to replicate it
