### ISSUE TITLE
Client crashes when breaking chests as a Piglin

### ISSUE THREAD

**Issue by EmilsGithub** [MoriyaShiine/extra-origins#227]
### Mod version (NOT Minecraft version)

extraorigins-1.20-6 (MC 1.20.1)

### A description of the issue

Breaking a chest as a Piglin causes a NullPointerException on the client that looks to be related to MobNeutralityPower.shouldBeNeutral.

This is in the overworld if that changes anything.

### Log or crash report

https://gist.github.com/EmilsGithub/84d29a5c0878f1a3f99b956f5fde2f02

**Comment by MoriyaShiine** [comment]
I'm unable to replicate this, could you do more testing please? Such as if it needs piglins nearby or anything else you can think of

**Comment by EmilsGithub** [comment]
Hi, did some testing and there were no piglins nearby. Really can't think of anything else causing this...

**Comment by MoriyaShiine** [comment]
Could you see if it happens on 1.20.2?

**Comment by EmilsGithub** [comment]
Yes, still happens on 1.20.2.

https://gist.github.com/EmilsGithub/ee96d0928b9055fab8caf0a2c2aacb87

Only using these mods this time and still in the Overworld. 
Fabric API
Pehkui
Origins
Extra Origins

**Comment by EmilsGithub** [comment]
Found out what causes it. (It's my friend that is crashing)

They first spawned with another origin, in the Overworld. 
Then they swapped to a Piglin and after breaking a chest they then crashed.

But if they visit the Nether they no longer crash.

I haven't read how your power works but could this be because it hasn't been "initialized" yet? Like it hasn't found any Piglins to apply it to and therefore it gives a NullPointerException?
