### ISSUE TITLE
Hoglins and Zoglins do not respect mob neutrality power.

### ISSUE THREAD

**Issue by JensenJ** [MoriyaShiine/extra-origins#229]
### Mod version (NOT Minecraft version)

1.20-11 for MC 1.20.2

### A description of the issue

I tried to create the following power file: https://gist.github.com/JensenJ/dc622030fb01dc8a4a77d21ae6d8c673
to make all mobs in the nether neutral as part of an origin.
Every mob in here is neutral except for the Hoglin when the power is applied. Briefly looking into the code within extra origins, it seems a mixin is applied into the Target Goal class which works well for every mob except the hoglin. It may be required to make some extra logic or a mixin specifically for the hoglin. Looking at Minecraft's source code the hoglin doesn't seem to use the goal system, or atleast not that I could see, but I did only look briefly.

### Log or crash report

https://gist.github.com/JensenJ/80ecc3abc044ccc801da490e3250a749

**Comment by MoriyaShiine** [comment]
I must have missed that; thanks for the report!
