### ISSUE TITLE
Nucleon Crashing Game

### ISSUE THREAD

**Issue by deviousdino** [MoriyaShiine/extra-origins#234]
### Mod version (NOT Minecraft version)

1.20-11 (does this on all nucleon versions, though)

### A description of the issue

Whenever the world loads and i pick nuclean, the game simply crashes with the error code
The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'boolean io.github.apace100.apoli.power.PowerType.isSubPower()'

### Log or crash report

https://gist.github.com/deviousdino/d3304b6ed42420f6cf0c9cef7e164c56

**Comment by deviousdino** [comment]
oops, forgot to say, i was trying all nuclean versions, i actually used -11 there, but it happens all the same for all versions, sorry!

**Comment by MoriyaShiine** [comment]
Your Origins versions seems out of date, does updating fix it?

**Comment by deviousdino** [comment]
> Your Origins version seems out of date, does updating fix it?

this seems to have fixed it, thanks!
