### ISSUE TITLE
[ 1.19.2 ] Crash Server Start

### ISSUE THREAD

**Issue by darkwolfie37** [MoriyaShiine/extra-origins#235]
### Confirmations

- [ ] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

From fabric.mod.json: "version": "1.19-2"

### A description of the issue

Crashes on server boot.

### Log or crash report

https://gist.github.com/darkwolfie37/87d9312b5f9ff2023198f8790582dd6f

**Comment by MoriyaShiine** [comment]
Clone of #218 

Either downgrade Fabric Loader to < 0.15.0, or install the patch mod pinned in the extra-origins channel in my discord. Updating to 1.20.1 or higher fixes this without the patch mod
