### ISSUE TITLE
failure to launch

### ISSUE THREAD

**Issue by superon** [MoriyaShiine/extra-origins#24]
this happens pretty quickly, i must be missing something unless it's something else
extraorigins-1.16.4-6
fabric-api-0.29.3+1.16

https://pastebin.com/yjGnbtS1
other mods:
modmenu-1.14.13+build.19
Origins-1.16.4-0.4.6
Origins-Classes-1.16.3-1.1.0
Pehkui-1.6.2+1.16.3

**Comment by antigamer101** [comment]
I am having the same problem, it tells me I need fabric loader but I already have fabric API unless it in another mod

**Comment by antigamer101** [comment]
what fabric loader version are you using? i had the same problem but it was fixed by downloading the latest version of fabric

**Comment by superon** [comment]
ahh yes, let me do that :)

**Comment by MoriyaShiine** [comment]
:ok_hand:
