### ISSUE TITLE
Game stops responding after choosing Inchling

### ISSUE THREAD

**Issue by godofwwa52000** [MoriyaShiine/extra-origins#26]
I have a lot of mods installed and every other origin works that I have tested but this is the only one I know that changes your size so that could be the issue. I have updated them to the most recent on Pehkui and the 1.16.4 version for Extraorigins and it crashes on startup. I can give a full list of mods if needed, it would just take some time, but since the game never actually crashes, its just stops responding, I do not get a crashlog. Any help would be great!

**Comment by MoriyaShiine** [comment]
I'm not sure what the issue is, but most 1.16.4 mods work on 1.16.5 without issue so I'd recommend updating. Let me know if it still causes a freeze :)

**Comment by MoriyaShiine** [comment]
No response, so assuming it works fine on 1.16.5
