### ISSUE TITLE
florans starve....

### ISSUE THREAD

**Issue by Worgrick** [MoriyaShiine/extra-origins#3]
I love the mod, but I wanted you to come up with away to deal florans not regenerating food in the end, nether or bad weather. They need to be able to eat dirt, or regenerante food around fire or something. 
Honestly I spend alot of time in the end late game, so this really effects the places I can live. and I'm sure others feel the same.
Thanks in advance for looking into this

**Comment by MoriyaShiine** [comment]
They're plants, plants can't survive in hellish temperatures or places with no sun. If you want to live in the nether, don't be a Floran :P

**Comment by Worgrick** [comment]
Listen I understand that but it also means I can't run this with primal winter. You see it never stops snowing. Also plants grow in the nether and the end and the bottom of the sea, plants in real life can do the and more. I know this is more stuff to do but think about it this is the nether update, and suddenly a huge portion of the game is cut off. Plus what would be the point of playing a thing that has zero survivability late game. Do you know how many farms are done through the nether or the end? Gold, wither roses, ender pearls, blaze powder, Elyria, shulker boxes, etc. Please reconsider, because this sounds like a fun race its just, inoperable at the moment. Also would you like me to send you the mod pack im working on, it uses your mod?

**Comment by CammiePone** [comment]
Yea, but Wor, those plants you mentioned don't photosynthesize. And sure, there are some plants that can live through harsh winters, but they're not the kind of plant the Floran was modeled after.
