### ISSUE TITLE
When I re enter my game I'm not small again.

### ISSUE THREAD

**Issue by EepChats** [MoriyaShiine/extra-origins#30]
Hi! I had this problem that when Im playing as the inchling and I re enter to the game it makes me normal sized again. Any way to fix this?

Oh and also when I go small it screws up the layer of my head. (pic related)
![unknown](https://user-images.githubusercontent.com/78998145/107843853-1c973580-6dd7-11eb-9938-c7931cb36cc2.png)

**Comment by MoriyaShiine** [comment]
The latest version of pehkui should have fixed this (the 1.17 snapshot one works on 1.16.5)
