### ISSUE TITLE
Missing overlay on head when using Inchling?

### ISSUE THREAD

**Issue by EepChats** [MoriyaShiine/extra-origins#31]
Hey sorry to bother again, but how do I fix it so that the overlay on my head doesnt screw up when I become Inchling? (Second picture how my head should look like)
![Screenshot_1](https://user-images.githubusercontent.com/78998145/107854236-4f671b00-6e23-11eb-893f-5c1b87518ca5.png)
![Screenshot_2](https://user-images.githubusercontent.com/78998145/107854237-50984800-6e23-11eb-9254-d0b4746148da.png)

**Comment by heartb33t** [comment]
i'm having this issue too!!

**Comment by AviceJaeger** [comment]
I think its due to the head being larger? although I gotta say, I do miss the details I added to my skin, hopefully there's a way to fix this in coding though
