### ISSUE TITLE
Server Crashes when trying to run extra origins mod

### ISSUE THREAD

**Issue by HenrryGamert** [MoriyaShiine/extra-origins#32]
extra origins crashes servers im in a origins smp server and we tried adding this but it crashes can you look into it? we are using the latest version of fabric api fabric launcher pehkui and extra origins on 1.16.5.I dont have the crash log because i dont own the server.

**Comment by MoriyaShiine** [comment]
I need a crash log or I can't help you.

**Comment by PaperPeyton21** [comment]
I am the owner of the server and I will try and get that crash log to you as soon as I am available.

**Comment by PaperPeyton21** [comment]
Also when it crashes it says that it doesn't recognize what the item extraorigins: liquid_sunlight is.

**Comment by MoriyaShiine** [comment]
Something caused the game to lag for too long and minecraft shut down the server because of it. Try installing Spark to see what's causing it.

**Comment by Fathamz** [comment]
Was this figured out? I am having the exact same problem and I have no clue how to fix it.

**Comment by JohnnySetback** [comment]
> Also when it crashes when joining the server it says that it doesn't recognize what the item extraorigins:liquid_sunlight is, or something like that.

It's like that for me, how do I fix it?
@PaperPeyton21

**Comment by MoriyaShiine** [comment]
Closing because no response from profiling, assuming fixed or bad server host
