### ISSUE TITLE
Piglin Origin Golden tools extra damage doesnt work

### ISSUE THREAD

**Issue by PigitWasTaken** [MoriyaShiine/extra-origins#33]
golden tools are meant to do +2 extra damage i tested this and it doesnt work

**Comment by Aelpecyem** [comment]
check again, just because it doesn't appear in the tooltip doesn't mean it does not apply

**Comment by PigitWasTaken** [comment]
i tested it i compared it with a iron sword and iron sword killed zombie in 3 hits while golden sword killed the zombie in 4 hits

**Comment by Aelpecyem** [comment]
that is literally impossible, do you have the origin selected

**Comment by Aelpecyem** [comment]
![2021-02-15_14 31 39](https://user-images.githubusercontent.com/41518251/107958332-24570580-6fa2-11eb-8309-b6b03f7877b3.png)
Here's an image for reference, the last stats refer to health before / after a full hit with a gold sword (which does 4 dmg by default)

**Comment by Aelpecyem** [comment]
I correct myself the last two are for a golden axe, which does 7 dmg by default
