### ISSUE TITLE
Extra Origins won't load on my server.

### ISSUE THREAD

**Issue by shrimpfellow** [MoriyaShiine/extra-origins#35]
I have an Apex Hosting server and I'm trying to get the Extra Origins mod on it. Originally, when I had tried to use it, it came up with a message saying that I needed Fabric Loader 0.11.0, which I downloaded (The server wouldn't start before I downloaded it). 
 
After that, it still kept telling me I needed Fabric Loader 0.11.0, so I tried putting the Extra Origins file into the Fabric Loader 0.11.0 file. It let me join the server, but the extra origins don't appear in the Origins menu. What do I do?

**Comment by MoriyaShiine** [comment]
You put it in the mods folder like any other mod, I have no idea what you're trying to do lol
