### ISSUE TITLE
Request of adding Chinese Simplified Translation

### ISSUE THREAD

**Issue by linzexin022** [MoriyaShiine/extra-origins#4]
Hi there, I'd like to add the Chinese Simplified Translation. here's the json file:

[zh_cn.txt](https://github.com/MoriyaShiine/extra-origins/files/5055058/zh_cn.txt)

(You just need to change .txt to .json)

**Comment by MoriyaShiine** [comment]
Send it as a pull request please.

**Comment by linzexin022** [comment]
Sorry about that, I'm not familiar with github... Can I ask how to use pull request to upload files?
