### ISSUE TITLE
Piglins cant drown/ Gold items issue

### ISSUE THREAD

**Issue by artzsocks** [MoriyaShiine/extra-origins#44]
Hey! Small issue, was playing as a piglin on a server will no enchantments/items but I was unable to lost any bubbles swimming in water.  It is consistent and has not changed, even with dying/logging in and logging out.  Hope its fixed soon!

I find that also, if i "incorrectly" use a gold item (say, break dirt accidentally with a pickaxe, or use an axe to kill something, it loses WAY more durability than it should.  I suspect this is the gold tool reverting back to its usual durability satus.

**Comment by MoriyaShiine** [comment]
Piglins become undead outside of the nether, so they don't need to breathe. Gold tool stuff should have been fixed in the latest version.
