### ISSUE TITLE
Power types?

### ISSUE THREAD

**Issue by MrCork** [MoriyaShiine/extra-origins#47]
I'm trying to find the list of power types for Extra Origins specifically, mostly for a datapack to modify the scale in a different way of the inchling. For example, the datapack I'm making is a Dwarf datapack, and I'm trying to set the player's scale to 0.6.

**Comment by Kobbruh** [comment]
{
    "type": "extraorigins:modify_size",
    "scale": x,
    "hidden": true
}

**Comment by MoriyaShiine** [comment]
There's a wiki tab on this github

**Comment by Kobbruh** [comment]
power types like modify_size aren't specified in the wiki for use though

**Comment by MoriyaShiine** [comment]
I can add it later
