### ISSUE TITLE
Nimble power type not working

### ISSUE THREAD

**Issue by Kobbruh** [MoriyaShiine/extra-origins#48]
whenever I try to use the power "extraorigins:nimble" it says that it is unrecognized and if I try to use it as a power type, it says it needs to be defined.

**Comment by Kobbruh** [comment]
I'm getting the same issue with "extraorigins:bigger_head" and "extraorigins:small_arms"

**Comment by ImHereForCurseForge** [comment]
Which powers are these? Powers you made? How did you made them? What did you do?

**Comment by MoriyaShiine** [comment]
These powers are used in the same way as vanilla Origins powers
