### ISSUE TITLE
Fish people can survive the nether but plant people can't.

### ISSUE THREAD

**Issue by Worgrick** [MoriyaShiine/extra-origins#5]
Fire gives Florian extra damage. But what if the floran went into a trance using the class ability, similar to sleeping its just you can be attacked. Also you should make it so florans set the ground on fire when they are. This still makes the nether a huge a Hazzard for the floran, because it means the cant even be on fire for a second in the nether, but have to stick around fire, because it is the only way to get food pops there.

**Comment by Worgrick** [comment]
Im not saying it has to be this. I just need a way to make this class to work, here is idea on how to make that balance out okay. Please work with me here I'll help however  I can.

**Comment by MoriyaShiine** [comment]
We already went over this in issue #3, don't spam issues.
