### ISSUE TITLE
Error Starting A Minecraft Server

### ISSUE THREAD

**Issue by MihneaSRO** [MoriyaShiine/extra-origins#53]
It says something about not recognising the item idk?
![image](https://user-images.githubusercontent.com/79604866/109060184-c8048c00-76ed-11eb-81a3-1a7bf5885e86.png)

![](https://cdn.discordapp.com/attachments/807002707259949069/814225156121034812/unknown.png)
 helpp

**Comment by MoriyaShiine** [comment]
You need it on both server and client

**Comment by MihneaSRO** [comment]
ty
