### ISSUE TITLE
i'm so confused??

### ISSUE THREAD

**Issue by RayExists** [MoriyaShiine/extra-origins#54]
When running the game, I am being met with an error message that says "Could not find required mod: extraorigins requires {origins @ [>=0.4.7]}

but i have the most recent version of both Origins and ExtraOrigins, and Pehkui

**Comment by MoriyaShiine** [comment]
"Most recent" doesn't say anything

**Comment by RayExists** [comment]
But do you know what I'm doing wrong?

**Comment by MoriyaShiine** [comment]
You need 0.4.7 installed

**Comment by RayExists** [comment]
And by 0.4.7 you mean..?
