### ISSUE TITLE
Inchling broken

### ISSUE THREAD

**Issue by thegamingdodo25** [MoriyaShiine/extra-origins#55]
When I got back online yesterday my inchling character got even smaller and lost the ability to crawl on blocks (still have no fall damage) I’m on a server

**Comment by AviceJaeger** [comment]
Hi! Do you per chance have the chisels and bits mod installed? We had the same issue due to that mod and I think we ended up fixing it.

**Comment by raccoonavi** [comment]
you can toggle the climbing ability for the inchling using the G key

**Comment by MoriyaShiine** [comment]
^ this is a vanilla origins power
