### ISSUE TITLE
Why does liquid sunlight not exist?

### ISSUE THREAD

**Issue by JohnnySetback** [MoriyaShiine/extra-origins#59]
When I go into a singleplayer server liquid sunlight just doesn't exist. If I try to join a multiplayer server that has this mod it says:

Registry remapping failed: Recieved ID map for minecraft:item contains IDs unknown to reciever! - extraorigins:liquid_sunlight

How do I fix this?

**Comment by MoriyaShiine** [comment]
Update both ends, I removed it

**Comment by aestorics** [comment]
help me
