### ISSUE TITLE
Glass Golem

### ISSUE THREAD

**Issue by MoonTheBird** [MoriyaShiine/extra-origins#62]
The glass golem is just. Gone. No explanation, no reasoning, nothing. It's just gone. Why?

**Comment by MoriyaShiine** [comment]
I removed it because the inchling now serves its purpose as a glass cannon. I may visit the idea again in the future though

**Comment by MoonTheBird** [comment]
How so? I don't see much about the inchling dealing more damage.

**Comment by MoriyaShiine** [comment]
Faster attack speed

**Comment by MoonTheBird** [comment]
That doesn't exactly feel like a very... fair reason to completely remove an entire origin.

**Comment by MoriyaShiine** [comment]
How so? They serve the same purpose but glass golem is worse. If you feel like discussing more, please join the discord, github issues is not the place

**Comment by MoonTheBird** [comment]
The discord link you have on your mod page no longer works.

**Comment by MoriyaShiine** [comment]
Works fine for me. https://cdn.discordapp.com/attachments/756208648711176314/815073778362220594/Screenshot_20210226-221103_DuckDuckGo.png

**Comment by Raphe9000** [comment]
Could you make a datapack for the glass golem so servers with glass golems can update without changing their origin?
