### ISSUE TITLE
Mod won't load

### ISSUE THREAD

**Issue by KagedInABox** [MoriyaShiine/extra-origins#65]
I've played Minecraft 1.16.5 before, and every other mod works. I do not know why this one doesn't.
![image](https://user-images.githubusercontent.com/79804173/109427655-61b78c00-79c1-11eb-8908-7c71a419dc86.png)

**Comment by MoriyaShiine** [comment]
Check if you're actually using 1.16.5

**Comment by HardHatNewt** [comment]
it's now saying that you need snapshot 21w03a for it to properly run
![image](https://user-images.githubusercontent.com/72465543/109575872-a83fe000-7ac0-11eb-91f3-5439a3059282.png)

**Comment by MoriyaShiine** [comment]
You need that pehkui version, not the Minecraft version
