### ISSUE TITLE
the mod not existing (i think)

### ISSUE THREAD

**Issue by Timinymi** [MoriyaShiine/extra-origins#70]
i downloaded the mod together with origins and origins classes, and also fiber launcher and the other thing i can't remember the name of. i put all 3 mods together with the other thing in the mods foldier of the minecraft appdata, and when i tried to launch the game with the fiber version, it says and i quote: "could not find required mod: extraorigins requires {pehkui @ [>=1.7.1+21w03a]}. it won't let me launch it. what do i do?

**Comment by Timinymi** [comment]
oh also when i removed it from the mods folder it worked just fine

**Comment by MoriyaShiine** [comment]
You need pehkui

**Comment by Timinymi** [comment]
what is pehkui exactly? im sorry if this is obvious

**Comment by MoriyaShiine** [comment]
Another mod
