### ISSUE TITLE
Error Loading the Mod

### ISSUE THREAD

**Issue by HayleeScribbles** [MoriyaShiine/extra-origins#75]
Every time I try and start up the game I get this message. Every mod I have downloaded is the latest version, so I'm not sure what is wrong (I have the origins mod, fabric-api, mob origins, extra origins, and pehkui).
<img width="315" alt="Capture" src="https://user-images.githubusercontent.com/80224557/110255816-defb7780-7f52-11eb-9c45-f07fdb0eb106.PNG">

**Comment by MoriyaShiine** [comment]
This immediately tells me origins is outdated, it needs to be updated
