### ISSUE TITLE
Random Death Using the Inchling

### ISSUE THREAD

**Issue by JareAborack** [MoriyaShiine/extra-origins#81]
Whenever I play as an inchling for long enough, no matter where I am or what I'm doing, I will occasionaly "Die" and when I hit respawn I do so at my "death point" I am still alive while "dead", and am capeable of being hit, being moved by water, and dieing for real.

I first noticed this with other mods installed, but I tried it again **with no other mods**, and a third time with optimization mods only (Lithium, Phosphor, Sodium), all three situations provided the same issue, with no variations in causation, or timing.

I have no Idea what is causing this, could someone please help explain and provide a solution?

**Comment by JareAborack** [comment]
*PS, I also tried this again in varing situations (being cramped, being in the open, being in the sky, being in the nether, varing health levels, nothing mattered.

**Comment by MoriyaShiine** [comment]
This is a vanilla bug with having less than 10 hearts
