### ISSUE TITLE
Not gaining slowness as a floran

### ISSUE THREAD

**Issue by missghostical** [MoriyaShiine/extra-origins#85]
Hey. I don't know what's happening. Even when I go to a desert or the nether, I don't get slowness even though I'm a floran. Is something wrong? I am using the Classes mod as well.

**Comment by MoriyaShiine** [comment]
What version of Extra Origins are you using

**Comment by missghostical** [comment]
1.1.1....
Well, I'm dumb lol. Thanks for answering, anyways :)
