### ISSUE TITLE
Inchling crashes my game everytime I try to join my server

### ISSUE THREAD

**Issue by scolbo** [MoriyaShiine/extra-origins#88]
So I'm using this mod here, Extra Origins, and I think, "Hmm, the inchling seems kinda neato," so I go to pick it, and my game crashes. I open my game again and rejoin, and it crashes again. The only way I can fix it is deleting the player-data. I do have Pehkui installed, however this is a modpack and not just one mod so that could participate in the issue. If I need to supply a modlist I will gladly.

**Comment by MoriyaShiine** [comment]
I need a log

**Comment by scolbo** [comment]
I'll get one, give me a moment.

**Comment by scolbo** [comment]
okay this might piss you off but i just reinstalled the mod and it works. idk what i did but it works?? sorry for wasting your time

**Comment by MoriyaShiine** [comment]
nice
