### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by S0mth1ngCr38t1v3** [MoriyaShiine/extra-origins#90]
I'm trying to host a server on shockbyte and everytime i go to get it is has an error saying " Registry remapping failed: Received ID map for minecraft:item contains IDs unknown to the receiver! - extraorigins:liquidsunlight ", I don't have extra origins on after resetting the server multiple times, how would I fix this?

**Comment by MoriyaShiine** [comment]
Shockbyte doesn't support 1.16.5 and that's the only version I support, I would ask them to let you use it
