### ISSUE TITLE
updating since extraorigins-1.16.5-2

### ISSUE THREAD

**Issue by superon** [MoriyaShiine/extra-origins#91]
i've been unable to update and still use the extra origins modified files.
i've combined Inchling with Arachnid, removed the option to chose Piglin and changed some things about Floran but all of the changes are being ignore on load, defaulting to standard..   all that is except for the Piglin removal.
i'd rather not start a supporting conversation here but i've also no permissions to post anywhere on the discord channel anymore.
also, was glass golem not extra origins?
doesn't seem to be, either way that's another thing (possibly custom thing) that's no longer being recognised by the game.

**Comment by MoriyaShiine** [comment]
Look at the roles channel

**Comment by superon** [comment]
i have, looked and clicked.. and restarted discord
