### ISSUE TITLE
Need Help With Custom Origin

### ISSUE THREAD

**Issue by WuddlesMC** [MoriyaShiine/extra-origins#92]
I'm trying to make a custom origin that uses scale (aiming for 1.5 scale), but I'm having issues getting it to appear on the menu. I've tried a datapack and adding an origin to the mod. Could I get some help?
`{
  "type": "origins:multiple",
  "modify_size": {
    "type": "extraorigins:modify_size",
    "scale": 1.5
  },
  "attribute_modifiers": {
    "modifiers": [
      {
        "name": "Origin modifier",
        "attribute": "generic.max_health",
        "value": 10,
        "operation": "addition"
      },
      {
        "name": "Origin modifier",
        "attribute": "generic.attack_speed",
        "value": -0.5,
        "operation": "addition"
      },
      {
        "name": "Origin modifier",
        "attribute": "generic.movement_speed",
        "value": -0.01,
        "operation": "addition"
      },
      {
        "name": "Origin modifier",
        "attribute": "reach-entity-attributes:reach",
        "value": -1,
        "operation": "addition"
      }
    ],
    "type": "origins:attribute"
  },
  "name": "Larger Than Life",
  "description": "While your size makes you stronger, you are slightly slower than most people"
}`
`{
  "powers": [
    "origins:carnivore",
    "origins:climbing",
    "origins:claustrophobia",
    "origins:fall_immunity",
    "origins:sprint_jump",
    "goliath:big",
    "origins:hunger_over_time"
  ],
  "icon": "minecraft:gilded_blackstone",
  "order": 5,
  "impact": 3,
  "name": "Goliath",
  "description": "A larger-than-life being,the Goliath is 1.5 blocks tall."
}`
`{
  "origins": [
    "goliath:goliath"
  ],
  "replace": false
} `

**Comment by MoriyaShiine** [comment]
Adding an origin has to be in the origins namespace, but this is better asked in the origins discord
