### ISSUE TITLE
Crashing game

### ISSUE THREAD

**Issue by Tiscool** [MoriyaShiine/extra-origins#93]
My game says failed to launch and crashes before I even get into the game.

**Comment by MoriyaShiine** [comment]
I need a log or I can't do anything

**Comment by Tiscool** [comment]
![image](https://user-images.githubusercontent.com/81452201/112706969-7165ab80-8e6d-11eb-9df3-0d3dce5272db.png)
Is this what you want.

**Comment by MoriyaShiine** [comment]
Install pehkui

**Comment by Expora09** [comment]
kekkers
