### ISSUE TITLE
glass golem removal in newer versions

### ISSUE THREAD

**Issue by SpinnyBoiii** [MoriyaShiine/extra-origins#94]
Hi, I've been busy editting several origin mods for a modded server with some mates and was using the inorganic skill for some golem-like origins, but this doesnt work as it used to anymore in the version i required when i upgraded the origins mod itself to 0.6.0
Is there any chance i could get some help with getting it working again? I've been attempting it myself, but I'm not really capable of anything other than editting and making .json files for powers and/or origins.
Sadly my only results are minecraft failing to load a new world(highest % progress i had was on a superflat world,which was only 15%)

**Comment by MoriyaShiine** [comment]
There's a data pack pinned in the discord for the glass golem since it doesn't need any extra code, you can take from it if you need
