### ISSUE TITLE
Game crashes on startup when combined with Lato Origins mod

### ISSUE THREAD

**Issue by TNSGJones** [MoriyaShiine/extra-origins#96]
Just found out that Extra Origins somehow collides with the Lato Origins mod.
Both mods work fine without the other one present.
Other mods are present as well but do not seem to interfere.

Log:
[latest.log](https://github.com/MoriyaShiine/extra-origins/files/6311240/latest.log)

**Comment by MoriyaShiine** [comment]
Is there a different log? This one doesn't tell me much

**Comment by TNSGJones** [comment]
Just downloaded it again to force a crash.

The startup log:
[2021-04-20-1.log](https://github.com/MoriyaShiine/extra-origins/files/6339937/2021-04-20-1.log)

No crashreport is being generated, and I feel like this one would be the same as the previous log.
Any idea where i can find information that could be helpfull for you?

**Comment by MoriyaShiine** [comment]
Someone told me Lato uses an outdated version of Pehkui, I can reopen if this wasn't the cause should they update
