### ISSUE TITLE
Death screen comes up before you die

### ISSUE THREAD

**Issue by glowmoss** [MoriyaShiine/extra-origins#97]
Someone on the server I am on tried playing hardcore and after getting hit once by a zombie the death screen came up and the zombie kept hitting them till they died. It seems to be the first time on any map the first hit brings up the death screen then it doesn't happen again. I tested on the latest version and the one before as we are using v10 but all the ones tested did the same thing only on Inchling

**Comment by MoriyaShiine** [comment]
This is a vanilla bug when you have more health than max health
